const on_Form_Submission = trigger({
  type: 'n8n-nodes-base.formTrigger',
  version: 2.6,
  config: { name: 'On Form Submission', parameters: { formTitle: 'Index a book', formDescription: 'Upload a PDF. Its text is cleaned, split into chunks, embedded and written to the documents_v2 table so the assistant can answer questions about it.', formFields: { values: [{ fieldLabel: 'Book (PDF)', fieldName: 'data', fieldType: 'file', acceptFileTypes: '.pdf', multipleFiles: false, requiredField: true }, { fieldLabel: 'Book title (optional)', fieldName: 'bookTitle', fieldType: 'text', requiredField: false }] }, responseMode: 'onReceived', options: { path: 'index-book-v2', appendAttribution: false, buttonLabel: 'Index this book', respondWithOptions: { values: { respondWith: 'text', formSubmittedText: 'Upload received. The book is being indexed, this takes a few minutes. You can close this page and open the chat panel.' } } } }, webhookId: '382876c3-9c1f-44a2-9059-0e898025924b', notes: 'Entry point of the indexing path. The uploaded PDF arrives as the binary field named data, which is the field name the Extract from File node reads by default. The webhook route was changed for this pipeline, so this form does not fight over the route of the first one.', notesInFlow: true }
});

const extract_PDF_Text = node({
  type: 'n8n-nodes-base.extractFromFile',
  version: 1.1,
  config: { name: 'Extract PDF Text', parameters: { operation: 'pdf', options: {} }, position: [220, 0], notes: 'Step one, extraction. Reads the uploaded PDF and returns the whole text in a single field. A scanned book with no text layer returns almost nothing and needs OCR before this workflow can do anything useful.', notesInFlow: true }
});

const clean_and_Group_Pages = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: { name: 'Clean and Group Pages', parameters: { mode: 'runOnceForAllItems', jsCode: '// Step two, cleaning and chunking.\n//\n// Extract from File hands the whole book over in a single text field, and a printed page is\n// not reliably recoverable from the text layer, so chunks are cut on a fixed character budget\n// instead. CHARS_PER_PAGE mirrors the density of an average printed page, which is what makes\n// the page numbers in the metadata meaningful rather than decorative.\n//\n// PAGES_PER_GROUP then decides the granularity. Four pages per chunk puts a typical book in\n// the 10 to 100 chunks per 100 pages range, and each chunk carries the page range it covers so\n// a retrieved excerpt stays legible on its own.\n\nconst CHARS_PER_PAGE = 1850;\nconst PAGES_PER_GROUP = 4;\nconst CHUNK_SIZE = CHARS_PER_PAGE * PAGES_PER_GROUP;\nconst MIN_CHUNK_CHARS = 400;\n\nconst source = $input.first().json;\nconst raw = String(source.text ?? source.data ?? \'\')\n  .replace(/\\s*\\b\\d{1,3}\\b\\s*/g, \' \')\n  .replace(/\\s{2,}/g, \' \')\n  .trim();\n\n// Cut on a sentence boundary when one sits near the target, so a chunk never ends mid word.\nfunction cutAt(text, target) {\n  if (text.length <= target) return text;\n  const window = text.slice(target - 400, target + 400);\n  const sentence = Math.max(window.lastIndexOf(\'. \'), window.lastIndexOf(\'? \'), window.lastIndexOf(\'! \'));\n  if (sentence > 0) return text.slice(0, target - 400 + sentence + 1);\n  const space = window.lastIndexOf(\' \');\n  if (space > 0) return text.slice(0, target - 400 + space);\n  return text.slice(0, target);\n}\n\nconst chunks = [];\nlet offset = 0;\n\nwhile (offset < raw.length) {\n  const piece = cutAt(raw.slice(offset, offset + CHUNK_SIZE), Math.min(CHUNK_SIZE, raw.length - offset)).trim();\n\n  if (piece.length >= MIN_CHUNK_CHARS) {\n    const fromPage = Math.floor(offset / CHARS_PER_PAGE) + 1;\n    const toPage = Math.max(fromPage, Math.ceil((offset + piece.length) / CHARS_PER_PAGE));\n\n    chunks.push({\n      chunk: chunks.length + 1,\n      fromPage,\n      toPage,\n      pages: toPage - fromPage + 1,\n      chars: piece.length,\n      text: \'[pages \' + fromPage + \'-\' + toPage + \'] \' + piece,\n    });\n  }\n\n  // Always move forward, even on a skipped piece, otherwise a tiny remainder loops forever.\n  offset += CHUNK_SIZE;\n}\n\nif (chunks.length === 0) {\n  throw new Error(\'The extracted PDF text is shorter than the minimum chunk size. It is probably a scan without a text layer, which needs OCR first.\');\n}\n\nreturn chunks;' }, position: [440, 0], notes: 'Step two, cleaning and chunking. Strips isolated page numbers and repeated spaces, then cuts the text into fixed character blocks on a sentence boundary when one is nearby. No chapter detection, so it behaves the same on a novel, a textbook or a paper. PAGES_PER_GROUP is the only knob: 4 pages gives about 25 chunks per 100 pages, 8 pages about 12.', notesInFlow: true }
});

const build_Embedding_Batches = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: { name: 'Build Embedding Batches', parameters: { mode: 'runOnceForAllItems', jsCode: '// Step three, turning chunks into Gemini batch requests.\n//\n// batchEmbedContents takes a list of texts in one call, so the whole book needs a handful of\n// requests instead of one per chunk. Each batch carries its chunk metadata so the vectors can be\n// paired back to their text afterwards, which is what happens inside the sub-workflow.\n\nconst BATCH_SIZE = 10;\n\nconst requests = $input.all().map((item) => ({\n  group: item.json,\n  request: {\n    model: \'models/gemini-embedding-001\',\n    content: { parts: [{ text: item.json.text }] },\n    taskType: \'RETRIEVAL_DOCUMENT\',\n    output_dimensionality: 1536,\n  },\n}));\n\nconst batches = [];\nfor (let i = 0; i < requests.length; i += BATCH_SIZE) {\n  batches.push({ json: { batch: batches.length + 1, requests: requests.slice(i, i + BATCH_SIZE) } });\n}\n\nreturn batches;' }, position: [640, 0], notes: 'Step three. Packs ten chunks into one Gemini batchEmbedContents request, at 1536 dimensions so pgvector can keep a real HNSW index. Kept small because one request must stay under the Gemini token rate, and the embedding node spaces the calls one minute apart.', notesInFlow: true }
});

const limit_Batches = node({
  type: 'n8n-nodes-base.limit',
  version: 1,
  config: { name: 'Limit Batches', parameters: { maxItems: 5 }, position: [860, 0], notes: 'Caps how many batches a single run embeds, which is what keeps the Gemini token rate and the execution timeout under control. Five batches of ten chunks indexes the first fifty chunks of a book. Raise it to index more in one pass, lower it to test the pipeline quickly.', notesInFlow: true }
});

const run_Chunking = node({
  type: 'n8n-nodes-base.executeWorkflow',
  version: 1.4,
  config: { name: 'Run Chunking', parameters: { workflowId: { __rl: true, mode: 'id', value: 'Abd2yYNGh1GHfMIR', cachedResultName: 'RAG Livre 2 Chunking' }, workflowInputs: { mappingMode: 'defineBelow', value: {}, matchingColumns: [], schema: [], attemptToConvertTypes: false, convertFieldsToString: true }, options: {} }, position: [1080, 0], notes: 'Calls the chunking sub-workflow, which owns the Gemini embedding call, the minute between calls and the SQL insert into documents_v2. It comes back as a short confirmation rather than the whole book, which keeps this workflow memory flat on a long document.', notesInFlow: true }
});

const verify_Index_Statistics = node({
  type: 'n8n-nodes-base.postgres',
  version: 2.7,
  config: { name: 'Verify Index Statistics', parameters: { operation: 'executeQuery', query: 'select count(*)::int as "ChunksIndexed",\n       min((metadata->>\'from_page\')::int) as "FirstPage",\n       max((metadata->>\'to_page\')::int) as "LastPage",\n       round(avg(length(content)))::int as "AverageChunkLength",\n       round(avg(vector_dims(embedding)))::int as "EmbeddingDimensions"\nfrom documents_v2;', options: {} }, credentials: { postgres: newCredential('Postgres account', '4ow0IG7roBxAxCIi') }, position: [1300, 0], notes: 'Reads documents_v2 straight over SQL to confirm what actually landed: how many chunks, which pages they cover and the vector dimension. This is the first thing to run whenever answers come back empty, because it separates a broken pipeline from a broken search.', notesInFlow: true }
});

const indexing_Report = node({
  type: 'n8n-nodes-base.set',
  version: 3.5,
  config: { name: 'Indexing Report', parameters: { assignments: { assignments: [{ id: 'report-status', name: 'status', value: 'indexed', type: 'string' }, { id: 'report-message', name: 'message', value: expr('{{ "Stored " + $json.ChunksIndexed + " chunks covering pages " + $json.FirstPage + " to " + $json.LastPage + " in documents_v2, averaging " + $json.AverageChunkLength + " characters at " + $json.EmbeddingDimensions + " dimensions." }}'), type: 'string' }] }, includeOtherFields: true, options: {} }, position: [1520, 0], notes: 'End of the indexing path. Turns the counted rows into a readable confirmation and keeps the raw counts beside it in the executions log.', notesInFlow: true }
});

const when_Chat_Message_Received = trigger({
  type: '@n8n/n8n-nodes-langchain.chatTrigger',
  version: 1.5,
  config: { name: 'When Chat Message Received', parameters: { public: true, options: { responseMode: 'streaming' } }, position: [0, 460], webhookId: 'a893e9d7-e173-4a79-96fd-af0e2a07cc32', notes: 'Entry point of the chat path. Public, so the hosted chat page opens from a link and works on a phone. It reads from documents_v2, so it only sees the books this pipeline indexed.', notesInFlow: true }
});

const embed_the_Question = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: { name: 'Embed the Question', parameters: { method: 'POST', url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent', authentication: 'predefinedCredentialType', nodeCredentialType: 'googlePalmApi', sendBody: true, specifyBody: 'json', jsonBody: expr('{{ { content: { parts: [{ text: $json.chatInput }] }, taskType: "RETRIEVAL_QUERY", output_dimensionality: 1536 } }}'), options: {} }, credentials: { googlePalmApi: newCredential('Google Gemini(PaLM) Api account 3', 'Gw0Xy0Xm4LdynEhK') }, position: [220, 460], notes: 'Chat step one. Embeds the question as a RETRIEVAL_QUERY so it lands in the same vector space as the chunks, which were embedded as RETRIEVAL_DOCUMENT. A mismatch here is the classic cause of answers that miss on obvious questions.', notesInFlow: true }
});

const search_Book_Content = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: { name: 'Search Book Content', parameters: { method: 'POST', url: 'https://kfkeothzelakkhnidtzd.supabase.co/rest/v1/rpc/match_documents_v2', authentication: 'predefinedCredentialType', nodeCredentialType: 'supabaseApi', sendBody: true, specifyBody: 'json', jsonBody: expr('{{ { query_embedding: $json.embedding.values, match_count: 5 } }}'), options: { timeout: 15000 } }, credentials: { supabaseApi: newCredential('Supabase account', 'MHWTeoHMJ0e03iJK') }, position: [440, 460], notes: 'Chat step two. Calls match_documents_v2 over PostgREST, which ranks chunks by cosine distance inside documents_v2 and returns the five closest. The URL carries the project reference, so it has to match your own Supabase project, and the schema cache has to be reloaded after the table is created.', notesInFlow: true }
});

const build_Grounded_Prompt = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: { name: 'Build Grounded Prompt', parameters: { mode: 'runOnceForAllItems', jsCode: '// Chat step three, assembling the prompt.\n//\n// The retrieved excerpts are the only source of truth. Each one already carries its page\n// range, so an answer can cite where it came from. Nothing here is specific to one book,\n// which is what lets the same chat path serve every book in documents_v2.\n\nconst rows = $json;\nconst question = $(\'When Chat Message Received\').first().json.chatInput ?? \'\';\nconst vector = $(\'Embed the Question\').first().json.embedding?.values ?? [];\n\nconst excerpts = (Array.isArray(rows) ? rows : [rows])\n  .slice(0, 5)\n  .map((row) => \'[\' + ((row.metadata?.from_page ?? \'?\') + \'-\' + (row.metadata?.to_page ?? \'?\')) + \'] \' + String(row.content ?? \'\'))\n  .join(\'\\n\\n---\\n\\n\');\n\nconst prompt =\n  \'You are a research assistant for books the user has uploaded.\\n\\n\' +\n  \'The excerpts below are the only source of truth. They come with the page range each one covers.\\n\\n\' +\n  \'- Ground every answer strictly in those excerpts. Never use your own knowledge of the books and never invent a detail, a quote or a name.\\n\' +\n  \'- If the excerpts do not contain the answer, say so plainly and suggest what to search instead.\\n\' +\n  \'- Quote briefly when it matters and cite the page range of the excerpt you used.\\n\' +\n  \'- Answer in the language used by the user.\\n\\n\' +\n  \'EXCERPTS\\n\' + excerpts + \'\\n\\nQUESTION\\n\' + question + \'\\n\\nANSWER\';\n\nreturn [{ json: { prompt, question, vector, excerpts } }];' }, position: [640, 460], notes: 'Chat step three. Assembles the grounding rules, the retrieved excerpts and the question into one prompt. The excerpt count is capped at five so a weak match cannot flood the context window.', notesInFlow: true }
});

const ask_Gemini = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: { name: 'Ask Gemini', parameters: { method: 'POST', url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent', authentication: 'predefinedCredentialType', nodeCredentialType: 'googlePalmApi', sendBody: true, specifyBody: 'json', jsonBody: expr('{{ { system_instruction: { parts: [{ text: "You are a careful research assistant. You only ever state facts that appear in the excerpts you are given, and you say so plainly when the excerpts do not answer the question." }] }, contents: [{ role: "user", parts: [{ text: $json.prompt }] }], generationConfig: { temperature: 0.2, maxOutputTokens: 4096 } } }}'), options: {} }, credentials: { googlePalmApi: newCredential('Google Gemini(PaLM) Api account 3', 'Gw0Xy0Xm4LdynEhK') }, position: [860, 460], notes: 'Chat step four. Asks Gemini for the answer at a low temperature, which keeps it close to the excerpts instead of wandering into its own knowledge.', notesInFlow: true }
});

const format_Reply = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: { name: 'Format Reply', parameters: { mode: 'runOnceForAllItems', jsCode: '// Chat step five, shaping the answer for the chat widget.\n//\n// The chat trigger streams whatever the last node returns under "output", so the Gemini\n// envelope has to be unwrapped here. A missing answer says so instead of showing nothing.\n\nconst body = $json;\nconst candidates = body?.candidates ?? [];\nconst text = candidates?.[0]?.content?.parts?.map((part) => part.text ?? \'\').join(\'\') ?? \'\';\n\nreturn [{ json: { output: text || \'I could not build an answer from the indexed excerpts.\' } }];' }, position: [1080, 460], notes: 'Chat step five. Reads the answer out of the Gemini response envelope and returns it as output, which is what the chat panel displays.', notesInFlow: true }
});

const wf = workflow('WiKRcLpzRdsJzhry', 'RAG Livre 2', { binaryMode: 'separate', executionOrder: 'v1', availableInMCP: true, description: 'Index a PDF book into a dedicated Supabase pgvector table with Gemini embeddings, where the embedding and the SQL insert live in a separate chunking sub-workflow, then answer questions about the indexed books in a chat powered by Gemini.' });

export default wf
  .add(on_Form_Submission)
  .to(extract_PDF_Text)
  .to(clean_and_Group_Pages)
  .to(build_Embedding_Batches)
  .to(limit_Batches)
  .to(run_Chunking)
  .to(verify_Index_Statistics)
  .to(indexing_Report)
  .add(when_Chat_Message_Received)
  .to(embed_the_Question)
  .to(search_Book_Content)
  .to(build_Grounded_Prompt)
  .to(ask_Gemini)
  .to(format_Reply)
  .add(sticky('## Two paths, two workflows\n\n**Row 1 - indexing, in this workflow**\n1. **Extract PDF Text** returns the whole text in one field.\n2. **Clean and Group Pages** strips page numbers and cuts the text into four page chunks.\n3. **Build Embedding Batches** packs ten chunks into one Gemini request.\n4. **Limit Batches** caps how many batches one run embeds, which is what bounds the token rate.\n5. **Run Chunking** calls the chunking sub-workflow and gets a short confirmation back.\n6. **Verify Index Statistics** counts the rows that actually landed in `documents_v2`.\n7. **Indexing Report** turns those counts into a readable confirmation.\n\n**Row 2 - chat, in this workflow**\n1. **Embed the Question** as a RETRIEVAL_QUERY.\n2. **Search Book Content** calls `match_documents_v2`, five closest chunks.\n3. **Build Grounded Prompt** assembles the rules, the excerpts and the question.\n4. **Ask Gemini** answers at temperature 0.2.\n5. **Format Reply** returns it as output.\n\n**The chunking sub-workflow**\nTrigger, **Embed Chunks**, **Merge Chunks with Vectors**, **Insert Chunks with SQL Query**, **Store Report**. It owns the embedding call, the minute between calls and the SQL insert, so a failed embedding can be retried without replaying the extraction.\n\n## Why characters and not chapters\nChunk boundaries follow a fixed character budget, so the pipeline never depends on reading a table of contents. It behaves the same on a novel, a textbook or a paper. Each chunk is prefixed with the page range it covers, so a retrieved excerpt stays legible on its own.\n\n## Tuning\n- **PAGES_PER_GROUP** in **Clean and Group Pages**: 4 pages gives about 25 chunks per 100 pages, 8 pages about 12, 2 pages about 50.\n- **Limit Batches**: 5 batches of 10 chunks indexes the first 50 chunks of a book.\n- **BATCH_SIZE** in **Build Embedding Batches**: raise it only if the Gemini token rate allows.\n\n## Uploading the same book twice\nThere is no deduplication. Uploading the same PDF twice stores the chunks twice, and the search then returns each excerpt in duplicate. Empty `documents_v2` first, or add a `book_id` column and filter on it.\n\n## Credentials\nPostgres on the insert node inside the sub-workflow and on the verification node here, Supabase API on the search node, Google Gemini on the embedding and generation nodes.', [], { name: 'Sticky Note RAG Livre 2 Usage', color: 2, width: 660, height: 900, position: [-700, 0] }))
  .add(sticky('## Supabase setup\n\nRun this once in the Supabase **SQL Editor** before the first upload. It creates a table that is separate from the first pipeline, so the two indexes never mix.\n\n```sql\ncreate extension if not exists vector;\n\ncreate table if not exists documents_v2 (\n  id bigserial primary key,\n  content text,\n  metadata jsonb,\n  embedding vector(1536)\n);\n\ncreate index if not exists documents_v2_embedding_idx\n  on documents_v2 using hnsw (embedding vector_cosine_ops);\n\ncreate or replace function match_documents_v2 (\n  query_embedding vector(1536),\n  match_count int default null,\n  match_threshold float default null\n)\nreturns table (\n  id bigint,\n  content text,\n  metadata jsonb,\n  similarity float\n)\nlanguage sql stable as $$\n  select\n    documents_v2.id,\n    documents_v2.content,\n    documents_v2.metadata,\n    1 - (documents_v2.embedding <=> query_embedding) as similarity\n  from documents_v2\n  order by documents_v2.embedding <=> query_embedding\n  limit match_count;\n$$;\n\nnotify pgrst, \'reload schema\';\n```\n\n## Why 1536 dimensions\npgvector refuses an HNSW index above 2000 dimensions, and Gemini returns 3072 by default. Asking for 1536 keeps a real HNSW index, so search stays fast as the library grows.\n\n## Four details that break it\n- The function must be named **match_documents_v2**, that is what the search node calls.\n- The search node URL carries the project reference, so it must match your own Supabase project.\n- Run `notify pgrst, \'reload schema\';` after creating the table, otherwise search fails with a schema cache 404.\n- The Postgres credential must point at the Supabase direct connection, and it needs the pooler in transaction mode, not session mode, so prepared statements survive the proxy.\n\n## Verifying without the workflow\n```sql\nselect count(*) from documents_v2;\n```\n\nIf that returns rows and the chat still answers empty, the problem is on the search side, not on the indexing side.', [], { name: 'Sticky Note RAG Livre 2 Supabase', color: 2, width: 660, height: 900, position: [-700, 940] }))